apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-k8s-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: docker-k8s-demo
  template:
    metadata:
      labels:
        app: docker-k8s-demo
    spec:
      containers:
      - name: docker-k8s-demo
        image: dnais1210/docker-k8s-demo:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: docker-k8s-demo-service
spec:
  selector:
    app: docker-k8s-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
